Iter9
oktavarium/go-gauger pull request #11
Opened 2023-09-24 19:22 UTC by oktavarium

2023-09-25 08:31 UTC, gonozov0 requested changes
Реализация огонь!) Было легко погрузиться в ревью. Предложил пару мелких необязательных улучшений + один критичный момент с интерфейсом архивариус

2023-09-25 08:31 UTC, gonozov0 commented on internal/agent/agent.go
> +				continue
Выглядит странно, почему решил игнорировать ошибку отправки метрик?

2023-09-25 08:31 UTC, gonozov0 commented on internal/models/models.go
> +type Metrics struct {
Не совсем понимаю, почему по заданию структура во множественном числе, я бы переименовал в Metric

2023-09-25 08:31 UTC, gonozov0 commented on internal/models/models.go
> +package models
Я так понимаю, это тут, т.к. используется одновременно в агенте и сервере. Я бы тогда называл пакет shared, чтобы было сразу понятно

2023-09-25 08:31 UTC, gonozov0 commented on internal/agent/metrics.go
> +		metrics.Value = &v
Вместо внешнего заполнения полей, я бы сделал 2 конструктора NewGaugeMetric и NewCounterMetric вызывал бы его тут их тут и ниже для Counter

2023-09-25 08:31 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/archivarius/interface.go
> +type Archivarius interface {
Получилась кажется абстракция над абстракцией, на мой взгляд, история с архивацией и чтением/записью в файл - это просто фича реализации InMemoryStorage.
То есть верхнеуровнего у нас должен быть как раз пакет storage, а внутри него в internal как раз archivarius. Если есть желание и время, я бы переделал

Но в целом, текущая реализация нас не заблокирует к будущей реализации [DBStorage](https://practicum.yandex.ru/learn/go-advanced/courses/6f379def-ed96-4f0f-b70e-5f61a5536e1a/sprints/140646/topics/64672fcf-b36d-497c-b341-be9bf5a8de5f/lessons/678bb794-6c3a-486b-9822-9ba82ce63d94/), т.к. интерфейсный подход все равно сохраняется.
Но тогда реализация базы данных у нас будет точно не часть пакета archivarius. Поэтому стоит положить этот интерфейс туда, где он используется (кажется в handlers) и переименовать его в Storage без какой либо связи с пакетом archivarius. Тогда в дальнейшем просто рядом сделаем пакет dbstorage, который также будет реализовывать этот интерфейс.

Выбери плиз, какой подход тебе больше импонирует, и поправь в соответствии с ним

2023-09-25 12:31 UTC, oktavarium commented on internal/agent/agent.go
> +				continue
Паника рушила тесты, когда сервер стартовал позже клиента - не мог отловить сразу в чем причина и погорячился во время отладки))

2023-09-25 12:32 UTC, oktavarium commented on internal/models/models.go
> +type Metrics struct {
согласен

2023-09-25 12:32 UTC, oktavarium commented on internal/models/models.go
> +package models
Готово

2023-09-25 12:32 UTC, oktavarium commented on internal/agent/metrics.go
> +		metrics.Value = &v
Готово

2023-09-25 12:41 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/archivarius/interface.go
> +type Archivarius interface {
Да тут беда в том, что не знаешь, что в итоге должно получиться в конце курса и приходится фантазировать на ходу, придумывая варианты, которые в моменте кажутся хорошими)) Я рассчитывал, что сохранение в файл будет общим для всех хранилищ в будущем, но раз нет, то твоя идея про упрятать в InMemoryStorage конечно лучше. 
Сразу вопрос) Когда появится DBStorage, то логичнее будет разделить пакет storage на два независимых или продолжать поддерживать все в одном?

2023-09-26 07:33 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/archivarius/interface.go
> +type Archivarius interface {
Думаю, что можно будет сделать независимые пакеты внутри storage, а интерфейс останется в том же месте

2023-09-26 07:34 UTC, gonozov0 approved these changes
Все замечания исправлены👍🏻

2023-09-26 07:58 UTC, merged