iter13
oktavarium/go-gauger pull request #17
Opened 2023-10-09 05:04 UTC by oktavarium

2023-10-09 09:53 UTC, gonozov0 requested changes
Отличная реализация 👍
Добавил пару моментов по улучшению кода

2023-10-09 09:53 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/handlers/get.go
>  		w.WriteHeader(http.StatusInternalServerError)
не заметил раньше, стоит добавить логирование самой ошибки

2023-10-09 09:53 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/batchupdate.go
> +	}
С точки зрения производительности это не оптимально, у тебя получится количество сетевых запросов на обновление столько же, сколько метрик пришло

Давай в цикле разделим метрики на 2 слайса по типу, а затем 2-мя запросами в базу обновим сразу все Gauge и Counter

Круто, что сразу реализовал все под транзакцией

2023-10-09 09:53 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/bootstrap.go
> +func (s *storage) bootstrap(ctx context.Context) error {
Не знаю рассказывали ли что-то по курсу про миграции к базам данных, но рекомендую почитать про `golang-migrate/migrate`, в последующем, если нам нужно будет что-то поменять в таблицах, нам понадобится полноценный механизм миграций

2023-10-09 09:53 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/save.go
> +	row := tx.QueryRowContext(ctx, "SELECT value FROM gauge WHERE name = $1", name)
Вместо дополнительного запроса на понимание, что нам нужна вставка или обновление данных, можно использовать в postgres фичу `ON CONFLICT DO UPDATE` при `INSERT`

2023-10-09 09:53 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/update.go
> +	row := tx.QueryRowContext(ctx, "SELECT value FROM counter WHERE name = $1", name)
Тут аналогично, при этом проблемы с инкрементом значения counter быть не должно, вот пример от chatgpt:

Да, в PostgreSQL при использовании `INSERT ... ON CONFLICT ... DO UPDATE` вы можете обращаться к текущим (т.е. "старым") значениям записи, которую вы пытаетесь обновить, используя ключевое слово `EXCLUDED`.

Представим, что у вас есть таблица `my_table` с первичным ключом `id` и числовым полем `value`. Если вы хотите увеличить значение `value` на 1 (или какое-либо другое число) в случае конфликта, вы можете сделать следующее:

```sql
INSERT INTO my_table (id, value)
VALUES (1, 1)
ON CONFLICT (id) DO UPDATE
SET value = my_table.value + 1;
```

В этом примере, если запись с `id = 1` уже существует, её значение `value` будет увеличено на 1. Если такой записи нет, то будет вставлена новая запись с `id = 1` и `value = 1`.

В общем случае, `EXCLUDED.column_name` представляет значение столбца, которое вы пытались вставить перед обнаружением конфликта. В нашем примере мы не использовали `EXCLUDED`, потому что нас интересовало текущее значение в таблице, а не то, которое мы пытались вставить.

2023-10-09 18:04 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/update.go
> +	row := tx.QueryRowContext(ctx, "SELECT value FROM counter WHERE name = $1", name)
Отличный совет, спасибо! Добавил еще и возвращаемое значение!

2023-10-09 18:05 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/save.go
> +	row := tx.QueryRowContext(ctx, "SELECT value FROM gauge WHERE name = $1", name)
Готово! Получилось гораздо элегантнее)

2023-10-09 18:05 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/bootstrap.go
> +func (s *storage) bootstrap(ctx context.Context) error {
Не, такой темы еще не было к сожалению. Спасибо за ссылку, изучу!

2023-10-09 18:06 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/batchupdate.go
> +	}
Перешел с sql.DB на pgx.Conn и сделал отправку через SendBatch

2023-10-09 18:08 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/handlers/get.go
>  		w.WriteHeader(http.StatusInternalServerError)
Добавил перехват ошибок в хэндерах через defer

2023-10-10 08:41 UTC, gonozov0 approved these changes

2023-10-10 09:47 UTC, merged