iter15
oktavarium/go-gauger pull request #19
Opened 2023-10-24 20:30 UTC by oktavarium

2023-10-27 11:45 UTC, s-shpak requested changes

2023-10-27 11:45 UTC, s-shpak commented on internal/agent/agent.go
> +		wg.Done()
Более идиоматичным было бы вызывать `wg.Done` вместе с `defer`: так ты даешь больше гарантий о том, что ты не забудешь его вызвать при выходе из функции

2023-10-27 11:45 UTC, s-shpak commented on internal/agent/agent.go
> +func fanIn(chs ...chan []byte) chan []byte {
Принимать на вход и отдавать лучше read-only каналы

2023-10-27 11:45 UTC, s-shpak commented on internal/agent/agent.go
> +		eg, time.Duration(flagsConfig.PollInterval*time.Second))
Не очень хорошо, что ты инициализируешь значение `PollInterval` при работе с флагами, а вычисляешь конкретное значение времени здесь. Если ты поменяешь флаг так, что теперь он будет принимать миллисекунды, ты можешь забыть поменять его здесь. Поэтому я бы вычислял duration там, где ты считываешь флаги и пишешь их в объект конфигурации

2023-10-27 11:45 UTC, s-shpak commented on internal/agent/flags.go
> +	if flagsConfig.RateLimit <= 0 {
То есть мы не можем отключить rate limiting, так и задумывалось?

2023-10-27 11:45 UTC, s-shpak commented on internal/agent/hash.go
> +	mac.Write(data)
Ошибки надо проверять

2023-10-27 11:45 UTC, s-shpak commented on internal/agent/metrics.go
> +	d time.Duration) chan []byte {
```suggestion
	d time.Duration,
) chan []byte {
```

2023-10-27 11:45 UTC, s-shpak commented on internal/server/internal/gaugeserver/internal/hash/hash.go
> +type hashedWriter struct {
Здесь можно использовать композицию, чтобы не переопределять методы `Header` и `WriteHeader`

2023-10-27 13:16 UTC, oktavarium commented on internal/agent/agent.go
> +		wg.Done()
Согласен, не досмотрел.

2023-10-27 13:16 UTC, oktavarium commented on internal/agent/agent.go
> +func fanIn(chs ...chan []byte) chan []byte {
Отличный совет, спасибо!

2023-10-27 13:17 UTC, oktavarium commented on internal/agent/flags.go
> +	if flagsConfig.RateLimit <= 0 {
Задание к инкременту написано очень путано и я понял его так, что это количество одновременных потоков, которые выполняют отправку на сервер, т.е. по умолчанию должен быть минимум 1.

2023-10-27 13:17 UTC, oktavarium commented on internal/agent/hash.go
> +	mac.Write(data)
Исправлено.

2023-10-27 13:17 UTC, oktavarium commented on internal/agent/metrics.go
> +	d time.Duration) chan []byte {
Не знал, что так красиво выравнивает. Исправил и другие длиннющие определения.

2023-10-27 13:17 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/hash/hash.go
> +type hashedWriter struct {
Супер! Спасибо!

2023-10-27 13:24 UTC, oktavarium commented on internal/agent/agent.go
> +		eg, time.Duration(flagsConfig.PollInterval*time.Second))
Опечатка) Флаги переделал в time.Duration, а тут исправить забыл. Аналогично исправил и в сервере.

2023-10-28 16:13 UTC, s-shpak approved these changes

2023-10-28 16:16 UTC, merged