Iter18
oktavarium/go-gauger pull request #20
Opened 2023-12-18 19:15 UTC by oktavarium

2023-12-26 08:38 UTC, gonozov0 requested changes
Отличная работа 👍
Внес много улучшений, особенно в плане документации
Оставил пару комментариев по коду
Так же подскажи плиз, удалось ли разобраться с pprof? Посмотреть визуально, какие части твоего кода дольше всего выполняются и занимают памяти.
Спрашиваю потому, что пообщавшись на 1:1 у многих не сложилось полное понимание, как он работает
https://app.pachca.com/chats?thread_id=2568500&sidebar_message=112734394

2023-12-26 08:38 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/handlers/value.go
> +			logger.Logger().Info("error",
Не совсем понимаю, почему ошибку логируешь, как info
\+ не совсем понимаю, зачем логировать через defer, у тебя вроде всего одно место где ошибка возникает.
Если считаешь, что много кода, чтобы каждый раз это вызывать, я бы тогда сделал какую-нибудь общую функцию LogError и вызывал бы ее явно в каждом месте

2023-12-26 08:38 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/handlers/value.go
> +			logger.Logger().Info("error",
Аналогичные ситуации есть в других частях проекта

2023-12-26 08:38 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/batchupdate.go
> +			err = tx.Rollback(ctx)
Обычно сразу же после создания транзакции вызывают просто `defer tx.Rollback(ctx)`
Если у тебя по итогу в функции отработал tx.Commit, то tx.Rollback вернет ошибку в момент исполнения и нам она не важна.
На мой взгляд такой подход более читабелен
Но не против, если оставишь свой вариант

2023-12-26 08:38 UTC, gonozov0 commented on internal/server/internal/gaugeserver/server_test.go
> -func testRequest(t *testing.T, ts *httptest.Server,
Почему решил удалить тесты?

2023-12-26 08:44 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/batchupdate.go
> +			err = tx.Rollback(ctx)
Изначально так у меня и было, но по неведомым причинам отказывалось работать )) Я читал, что `defer tx.Rollback(ctx)` не будет откатываться, если коммит был успешен, но у меня удалось воспроизвести обратное поведение - коммит совершался, а потом роллбэк его откатывал. Может конечно не досмотрел чего.

2023-12-26 23:36 UTC, oktavarium commented on internal/server/internal/gaugeserver/server_test.go
> -func testRequest(t *testing.T, ts *httptest.Server,
опечатка вкралась( вернул на место

2023-12-26 23:49 UTC, oktavarium commented on internal/server/internal/gaugeserver/internal/handlers/value.go
> +			logger.Logger().Info("error",
исправил на функцию логирования.

2023-12-27 00:02 UTC, oktavarium commented
> Отличная работа 👍 Внес много улучшений, особенно в плане документации Оставил пару комментариев по коду Так же подскажи плиз, удалось ли разобраться с pprof? Посмотреть визуально, какие части твоего кода дольше всего выполняются и занимают памяти. Спрашиваю потому, что пообщавшись на 1:1 у многих не сложилось полное понимание, как он работает https://app.pachca.com/chats?thread_id=2568500&sidebar_message=112734394

Да, с pprof разобраться удалось - посчастливилось попробовать его еще до спринта.

2023-12-27 09:43 UTC, gonozov0 commented on internal/server/internal/gaugeserver/internal/storage/internal/pg/batchupdate.go
> +			err = tx.Rollback(ctx)
Странно, скорее всего commit на самом деле по какой-то причине не отрабатывал у тебя в коде

2023-12-27 09:43 UTC, gonozov0 approved these changes
Работа принята 👍
Все моменты поправлены

2024-01-30 09:19 UTC, merged