Iter20
oktavarium/go-gauger pull request #22
Opened 2024-01-15 19:46 UTC by oktavarium

2024-01-16 08:37 UTC, gonozov0 requested changes
Отличная работа, внес много улучшений 👍
Но я не увидел реализацию 19-го инкремента, где необходимо написать свой exitchecker и свой линтер, включающий exitchecker + готовые стандартные анализаторы

2024-01-16 08:37 UTC, gonozov0 commented on .github/workflows/mertricstest.yml
> +          github.head_ref == 'iter24'
Отличная попытка, но недавно неприятно удивился, что автотестов после 14-й итерации для devops трека попросту нет)

2024-01-16 08:37 UTC, gonozov0 commented on Makefile
> +	go test ./... -coverprofile cover.out && go tool cover -func cover.out
Стоит добавить аргумент `-count=1` при запуске `go test`, иначе у тебя может использоваться кеш от предыдущих запусков и по итогу coverage будет не полный

2024-01-16 11:38 UTC, oktavarium commented on .github/workflows/mertricstest.yml
> +          github.head_ref == 'iter24'
ага, печаль)

2024-01-16 11:39 UTC, oktavarium commented on Makefile
> +	go test ./... -coverprofile cover.out && go tool cover -func cover.out
спасибо, поправил!

2024-01-16 11:39 UTC, oktavarium commented
> Отличная работа, внес много улучшений 👍 Но я не увидел реализацию 19-го инкремента, где необходимо написать свой exitchecker и свой линтер, включающий exitchecker + готовые стандартные анализаторы

опечатка с гитигнор - не залились изменения

2024-01-17 08:45 UTC, gonozov0 approved these changes
Оставил еще комменты по улучшениям, но все они опциональные
Поэтому заранее поставлю апрув 👍

2024-01-17 08:45 UTC, gonozov0 commented on internal/staticlint/exit.go
Весь пакет разумнее будет положить в pkg, т.к. этот линтер можно легко скопипастить в любой другой проект

2024-01-17 08:45 UTC, gonozov0 commented on internal/staticlint/testdata/pkg1/pkg1.go
Стоит еще добавить тесты на позитивный сценарий, что линтер отрабатывает без ошибок, когда нету os.Exit

2024-01-17 08:45 UTC, gonozov0 commented on Makefile
> +build:
Я бы еще предложил добавить команду lint, которая будет запускать staticlint

2024-01-30 09:19 UTC, merged