Iter23
oktavarium/go-gauger pull request #23
Opened 2024-01-28 18:59 UTC by oktavarium

2024-01-30 08:38 UTC, gonozov0 requested changes
Вмерджи плиз инкременты предыдущего спринта
https://github.com/oktavarium/go-gauger/pull/22

В этом пр много изменений, хотя часть изменений уже была отревьюена
Должны остаться только изменения 21-23 инкрементов

2024-01-30 08:38 UTC, gonozov0 commented on cmd/agent/main.go
> +		buildVersion, buildDate, buildCommit)
Как будто бы go fmt не отработал

2024-01-30 08:38 UTC, gonozov0 commented on cmd/server/main.go
> +		buildVersion, buildDate, buildCommit)
аналогично

2024-01-30 10:05 UTC, oktavarium commented on cmd/agent/main.go
> +		buildVersion, buildDate, buildCommit)
а он и не пытается заменять) 
поправил вручную

2024-01-31 13:52 UTC, gonozov0 approved these changes
Отличная работа 👍
Особенно классно, что не забыл про тесты
Оставил комментарий, но апрувну заранее, там все понятно по исправлениям

2024-01-31 13:52 UTC, gonozov0 commented on internal/server/internal/gaugeserver/server.go
> +		idleConnsClosed <- struct{}{}
Есть же WaitGroup, через нее будет понятнее код + через defer будет безопаснее

2024-01-31 19:49 UTC, oktavarium commented on internal/server/internal/gaugeserver/server.go
> +		idleConnsClosed <- struct{}{}
Отличный совет! Спасибо, исправил!!

2024-01-31 19:50 UTC, merged