Iter25
oktavarium/go-gauger pull request #24
Opened 2024-02-11 16:50 UTC by oktavarium

add grpc functionality

2024-02-12 10:37 UTC, gonozov0 requested changes
Отличная работа 👍
Оставил комменты по улучшению кода
Также не увидел тестов на grpc хендлеры, напиши хотя бы на 1, чтобы получить опыт

2024-02-12 10:37 UTC, gonozov0 commented on api/metrics.go
Я думаю этот код стоит перенести туда, где он используется. Мешать логику конвертации в структуры бизнес логики в пакете с proto файлами и сгенерированным кодом не стоит

2024-02-12 10:37 UTC, gonozov0 commented on internal/agent/ip.go
> +				return addr.String(), nil
Думаю где-то такой подход может приводить к неожиданным ошибкам. ChatGPT предложил такое:

Да, ваш подход к получению локального IP-адреса уже достаточно хорош, но есть несколько аспектов, которые можно улучшить для более точного и надежного результата. Например, ваш текущий код возвращает адрес сразу же после обнаружения первого доступного, не учитывая, является ли он внутренним (частным) IP-адресом или нет, и не проверяет, является ли интерфейс активным и поддерживает ли он IP связь.

Вот более точный способ получения локального IP-адреса, который фильтрует только активные интерфейсы, поддерживающие IPv4, и исключает локальный адрес обратной связи (127.0.0.1):

```go
package agent

import (
	"fmt"
	"net"
)

func getLocalIP() (string, error) {
	ifaces, err := net.Interfaces()
	if err != nil {
		return "", fmt.Errorf("error on getting interfaces: %w", err)
	}

	for _, iface := range ifaces {
		// Проверяем, что интерфейс активен и не является loopback
		if iface.Flags&net.FlagUp == 0 || iface.Flags&net.FlagLoopback != 0 {
			continue // Интерфейс не активен или является loopback
		}

		addrs, err := iface.Addrs()
		if err != nil {
			continue // Пропускаем интерфейс, если возникла ошибка при получении адресов
		}

		for _, addr := range addrs {
			// Проверяем, что адрес является сетевым адресом IPv4
			ipNet, ok := addr.(*net.IPNet)
			if !ok || ipNet.IP.To4() == nil {
				continue // Это не IPv4
			}

			// Исключаем локальный адрес обратной связи
			if ipNet.IP.IsLoopback() {
				continue
			}

			return ipNet.IP.String(), nil // Возвращаем первый подходящий адрес
		}
	}

	return "", fmt.Errorf("local IP address not found")
}
```

Этот код проходит по всем сетевым интерфейсам, проверяет, что интерфейс активен и не является loopback (127.0.0.1), а затем проверяет каждый адрес, привязанный к интерфейсу, чтобы убедиться, что он соответствует IPv4 и не является адресом обратной связи. Это обеспечивает, что возвращается действительный локальный IP-адрес, который может быть использован для сетевого взаимодействия в локальной сети.

2024-02-12 20:49 UTC, oktavarium commented on internal/agent/ip.go
> +				return addr.String(), nil
с ИИ не поспоришь)) Спасибо за совет!!

2024-02-12 20:49 UTC, oktavarium commented on api/metrics.go
да, согласен, перенес

2024-02-13 07:26 UTC, gonozov0 approved these changes
Апрув 👍

2026-08-08 12:30 UTC, merged