Iter5
oktavarium/go-gauger pull request #5
Opened 2023-09-04 07:27 UTC by oktavarium

2023-09-05 18:28 UTC, gonozov0 requested changes
Отличная работа!) Есть лишь небольшие замечания по структуре файлов, давай их пофиксим, это поможет в дальнейшем быстрее вносить новые изменения и расширять функциональность

2023-09-05 18:28 UTC, gonozov0 commented on internal/server/server.go
> +type metricsSaver interface {
Интерфейс принято класть рядом с его имплементацией. Давай положим в пакет storage в файл interface.go, а здесь будем импортировать
Также рекомендую сам интерфейс назвать Storage, а его реализацию хранения в оперативной памяти InMemoryStorage

2023-09-05 18:28 UTC, gonozov0 commented on internal/server/server.go
> +func (g *GaugerServer) updateHandle(w http.ResponseWriter, r *http.Request) {
Рекомендую разбивать файлы, где больше 100 строк, на мелкие логичные единицы, чтобы код было легче воспринимать, читать и понимать. В данном случае стоит переложить все хендлеры в отдельный   модуль, в нем по файлу на каждый хендлер

2023-09-05 18:28 UTC, gonozov0 commented on cmd/server/main.go
> +	fmt.Println("Running server on", flagsConfig.Address)
Для вывода логов о состоянии сервера и запросах рекомендую использовать лучше [logger middleware в chi](https://go-chi.io/#/pages/middleware?id=logger), но не настаиваю, явный и простой подход всегда имеет место быть 👍

2023-09-05 18:28 UTC, gonozov0 commented on cmd/server/main.go
> +		return err
Рекомендую всегда оборачивать возвращаемую ошибку в осмысленный текст, чтобы понимать, в каком месте она произошла
К примеру:
```go
return fmt.Errorf("error parse flags: %w", err)
```
Давай также сделаем и в других местах, где просто возвращается ошибка

2023-09-05 18:28 UTC, gonozov0 commented on cmd/server/main.go
> +func run() error {
Файл main.go обычно делают очень простым и без каких-либо дополнительных файлов рядом, всю бизнес логику, включая сетап конфига уносят в internal. Давай это унесем вместе с конфигом в пакет server, а в main будет вызывать server.Run()

2023-09-05 18:28 UTC, gonozov0 commented on cmd/server/flags.go
> +var flagsConfig config
Получается неявно, что переменная объявлена в одном файле, а используется в другом, рекомендую функцию parseFlags переделать под LoadConfig и возвращать из нее конфиг

2023-09-05 18:28 UTC, gonozov0 commented on cmd/agent/main.go
> +func run() error {
Это уже бизнес логика, давай все кроме main унесем в internal/agent и тут будет вызываться agent.Run()

2023-09-06 16:15 UTC, gonozov0 requested changes
Привет!) Осталась еще небольшая пара моментов по структуре кода, давай сделаем так, чтобы в internal у нас было только 2 пакета, разделяющие наши 2 решени agent и server. Все другие пакеты, что используется только для сервера, по типу storage и внутренняя структуры сервера давай поместим в server

2023-09-06 16:15 UTC, gonozov0 commented on internal/handlers/handlers.go
> +	handleType  string     = "update"
Не вижу, чтобы такой тип где-то использовался, если это действительно так, то лучше удалить

2023-09-06 16:15 UTC, gonozov0 commented on internal/server/server.go
> +	handler := handlers.NewHandler(storage)
Т.к. ты реализовал отдельную структуру сервера, то эту логику стоит поместить в NewGaugerServer, весь пакет хендлеров я бы поместил в internal/server/gaugeserver/internal/handlers, т.к. по своей зоне ответственности нигде кроме инициализации урлов сервера хендлеры не должны использоваться

2023-09-06 16:21 UTC, gonozov0 commented
Рекомендую почитать про подход Clean Architecture в данном шаблоне:
https://github.com/evrone/go-clean-template

2023-09-06 17:52 UTC, oktavarium commented on internal/handlers/handlers.go
> +	handleType  string     = "update"
Нет, это используется в хэндлерах - не могу удалить)

2023-09-06 17:52 UTC, oktavarium commented on internal/server/server.go
> +	handler := handlers.NewHandler(storage)
Засунул и gaugeserver в internal заодно

2023-09-07 08:10 UTC, gonozov0 approved these changes

2023-09-07 08:49 UTC, merged